name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          
      - name: Install dependencies
        run: npm install
        
      - name: Update CSS path in HTML
        run: |
          echo "Текущее содержимое (до замены):"
          grep -o "href=\"[^\"]*index.css\"" index.html
          sed -i 's|\./dist/index.css|\./styles/index.css|g' index.html
          echo "После замены:"
          grep -o "href=\"[^\"]*index.css\"" index.html
          
      - name: Verify HTML file
        run: |
          echo "Проверка содержимого HTML файла после замены:"
          cat index.html | grep -A 1 -B 1 stylesheet
          
      - name: Build project
        run: npm run build
        
      - name: Final Verification
        run: |
          echo "Финальная проверка HTML файла:"
          cat index.html | grep -A 1 -B 1 stylesheet
          echo "Проверка наличия CSS файла:"
          ls -la styles/
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .