name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          
      - name: Install dependencies
        run: npm install
        
      - name: Prepare for deploy
        run: npm run prepare-deploy  # Сначала меняем пути
        
      - name: Build project
        run: npm run build  # Потом собираем проект
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Публикуем весь проект